name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create deployment package
      run: |
        mkdir -p dist
        zip -r dist/opitios-alpaca-$(date +%Y%m%d-%H%M%S).zip . \
          -x "venv/*" "tests/*" ".git/*" "*.pyc" "__pycache__/*" ".env" \
          "*.log" ".pytest_cache/*" ".coverage" "htmlcov/*"
    
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v3
      with:
        name: deployment-package
        path: dist/
        retention-days: 30
    
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Opitios Alpaca Trading API Release
          
          ### Features
          - Real-time stock quotes (single and batch)
          - Options pricing with real market data
          - Paper Trading integration
          - FastAPI with comprehensive documentation
          - 34 real API tests (no mocks)
          
          ### API Endpoints
          - `/api/v1/stocks/quote` - Get stock quotes
          - `/api/v1/stocks/quotes/batch` - Batch stock quotes
          - `/api/v1/options/quote` - Get option quotes
          - `/api/v1/options/quotes/batch` - Batch option quotes
          - `/api/v1/stocks/order` - Place stock orders
          - Complete Swagger documentation at `/docs`
          
          ### Requirements
          - Python 3.9+
          - Alpaca Paper Trading API credentials
          - See README.md for setup instructions
        draft: false
        prerelease: false