name: Test with Real API Credentials

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      run_full_tests:
        description: 'Run full API tests (requires secrets)'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  test-with-real-api:
    runs-on: ubuntu-latest
    if: github.event.inputs.run_full_tests == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade pip-tools
        # Install dependencies with retries and better error handling
        pip install --no-cache-dir --timeout 1000 --retries 5 -r requirements.txt
        pip install pytest pytest-asyncio
    
    - name: Create secrets.yml file
      run: |
        cat > secrets.yml << 'EOF'
        # Multi-Account Configuration for CI/CD
        accounts:
          account_001:
            name: "CI Test Account"
            api_key: "${{ secrets.ALPACA_API_KEY }}"
            secret_key: "${{ secrets.ALPACA_SECRET_KEY }}"
            paper_trading: true
            tier: "standard"
            max_connections: 3
            enabled: true

        # JWT Configuration
        jwt:
          secret: "test-jwt-secret-for-ci"
          algorithm: "HS256"
          expiration_hours: 24

        # Trading Configuration
        trading:
          real_data_only: true
          enable_mock_data: false
          strict_error_handling: true
          max_option_symbols_per_request: 20
        EOF
    
    - name: Test Multi-Account System
      run: |
        python test_system_validation.py
    
    - name: Run Account Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        # Test account functionality
        python test_accounts.py
        
    - name: Run Trading System Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        # Test trading system
        python test_trading_simple.py