name: Test with Real API Credentials

on:
  workflow_dispatch:  # Manual trigger only
    inputs:
      run_full_tests:
        description: 'Run full API tests (requires secrets)'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  test-with-real-api:
    runs-on: ubuntu-latest
    if: github.event.inputs.run_full_tests == 'true'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
    
    - name: Create .env file
      run: |
        echo "ALPACA_API_KEY=${{ secrets.ALPACA_API_KEY }}" >> .env
        echo "ALPACA_SECRET_KEY=${{ secrets.ALPACA_SECRET_KEY }}" >> .env
        echo "ALPACA_BASE_URL=https://paper-api.alpaca.markets" >> .env
        echo "ALPACA_PAPER_TRADING=true" >> .env
    
    - name: Test API Connection
      run: |
        python -c "
        import asyncio
        from app.alpaca_client import AlpacaClient
        async def test():
            client = AlpacaClient()
            result = await client.test_connection()
            print('Connection test:', result.get('status', 'failed'))
            if result.get('status') == 'connected':
                print('✓ API credentials are valid')
                exit(0)
            else:
                print('❌ API credentials failed')
                exit(1)
        asyncio.run(test())
        "
    
    - name: Run Real API Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        # Run tests that actually connect to Alpaca API
        pytest tests/test_real_trading.py::TestRealAlpacaConnection::test_real_connection -v
        pytest tests/test_real_trading.py::TestRealStockData::test_real_single_stock_quote -v
        pytest tests/test_real_trading.py::TestRealStockData::test_real_multiple_stock_quotes -v